apiVersion: v2
name: rancher-webhook
description: ValidatingAdmissionWebhook for Rancher types
version: 0.0.0
appVersion: 0.0.0
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: cattle-system
  catalog.cattle.io/release-name: rancher-webhook
  catalog.cattle.io/os: linux
  catalog.cattle.io/rancher-version: '< 2.6.0-0'
  catalog.cattle.io/kube-version: '>= 1.16.0-0 < 1.25.0-0'
